In [2]:
1+1

2

In [3]:
def print_hello():
    print('hello')
    
print_hello()

hello


In [4]:
import numpy as np

In [5]:
class Hello():
    def __init__(self, to_say):
        self.to_say = to_say
        
    def say_it(self):
        print(f'hello {self.to_say}')

In [6]:
h = Hello('Hakan')

In [7]:
h.say_it()

hello Hakan


In [8]:
print_hello()

hello


## Workshop

- Thing 1
- Thing 2
Link: http://fast.ai

---

In [11]:
a = [1,2]; a

[1, 2]

In [12]:
for i in range(5): print(i+1)

1
2
3
4
5


In [25]:
# a = [... for i in ...]; a
a = [i+1 for i in range(5)]; a

[1, 2, 3, 4, 5]

In [23]:
[i*2 for i in a]

[2, 6, 10, 14, 18]

In [24]:
def modify_a(it): return it * 2 + 1

In [26]:
a = [modify_a(i) for i in range(5)]; a

[1, 3, 5, 7, 9]

A reduction in Informatics takes a list and returns a reduction.
Example: the sum() operation

In [27]:
sum(a)

25

In [35]:
def modify_a(it): return [str(it*2+1)]

Map / Reduce:

In [36]:
a = [modify_a(i) for i in range(5)]; a

[['1'], ['3'], ['5'], ['7'], ['9']]

In [37]:
sum(a, [])

['1', '3', '5', '7', '9']

Filter

In [38]:
a = [modify_a(i) for i in range(5) if i%2==0]; a

[['1'], ['5'], ['9']]

In [41]:
sum(a, [])

['1', '5', '9']

In [43]:
{'a':1, 'b':2}

{'a': 1, 'b': 2}

In [46]:
v = ['the', 'a', 'you']; v

['the', 'a', 'you']

In [48]:
[(i,w) for i,w in enumerate(v)]

[(0, 'the'), (1, 'a'), (2, 'you')]

In [49]:
{w:i for i,w in enumerate(v)}

{'a': 1, 'the': 0, 'you': 2}

In [50]:
import numpy as np

In [51]:
a = np.array([1,2,3]); a

array([1, 2, 3])

In [52]:
a*2

array([2, 4, 6])

In [53]:
a = np.array([1.1, 2.3, -3]);a

array([ 1.1,  2.3, -3. ])

In [54]:
a*2

array([ 2.2,  4.6, -6. ])

In [55]:
a.round(1)

array([ 1.1,  2.3, -3. ])